### ISSUE TITLE
macos arm - can't find ncurses

### ISSUE THREAD

**Issue by Bellavene** [timdubbins/tap#13]
Looks like it tries to use homebrew's path for intel... For arm the path is `/opt/homebrew/`

```
dyld[36739]: Library not loaded: /usr/local/opt/ncurses/lib/libncursesw.6.dylib
  Referenced from: <7326D888-57B8-37D7-835F-7F5F4A952A08> /opt/homebrew/Cellar/tap/0.4.11/bin/tap
  Reason: tried: '/usr/local/opt/ncurses/lib/libncursesw.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/ncurses/lib/libncursesw.6.dylib' (no such file), '/usr/local/opt/ncurses/lib/libncursesw.6.dylib' (no such file), '/usr/local/lib/libncursesw.6.dylib' (no such file), '/usr/lib/libncursesw.6.dylib' (no such file, not in dyld cache)
[1]    36739 abort      tap
```

**Comment by timdubbins** [comment]
Sorry I missed this issue. If you run 

brew reinstall ncurses
brew link ncurses

this might resolve this issue.

**Comment by wuhhh** [comment]
Confirm this is still an issue and the suggested workaround doesn't resolve it, was excited to try this at it looks great!

**Comment by timdubbins** [comment]
Thanks for confirming this. I've been working on tap recently and have an update to release, I will address this issue with the update (hopefully over the weekend)

**Comment by timdubbins** [comment]
Hi, this should be fixed with v0.5.0 although I don't have access to a Silicon mac to verify

**Comment by wuhhh** [comment]
I wish I had good news for you!

```
dyld[66629]: Library not loaded: /usr/local/opt/ncurses/lib/libncursesw.6.dylib
  Referenced from: <EFD5935E-3889-3A6A-8269-2C343E1A8827> /opt/homebrew/Cellar/tap/0.5.0/bin/tap
  Reason: tried: '/usr/local/opt/ncurses/lib/libncursesw.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/ncurses/lib/libncursesw.6.dylib' (no such file), '/usr/local/opt/ncurses/lib/libncursesw.6.dylib' (no such file)
[1]    66629 abort      tap
```

Did verify that ncurses is installed, also removed and installed it again as well as unlinked and linked it.

**Comment by timdubbins** [comment]
> I wish I had good news for you!
> 
> ```
> dyld[66629]: Library not loaded: /usr/local/opt/ncurses/lib/libncursesw.6.dylib
>   Referenced from: <EFD5935E-3889-3A6A-8269-2C343E1A8827> /opt/homebrew/Cellar/tap/0.5.0/bin/tap
>   Reason: tried: '/usr/local/opt/ncurses/lib/libncursesw.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/ncurses/lib/libncursesw.6.dylib' (no such file), '/usr/local/opt/ncurses/lib/libncursesw.6.dylib' (no such file)
> [1]    66629 abort      tap
> ```
> 
> Did verify that ncurses is installed, also removed and installed it again as well as unlinked and linked it.

Thanks very much for testing this. This *should* be fixed in v0.5.1!

**Comment by zkvsky** [comment]
@timdubbins you should consider dropping ncurses and just go with crossterm, which is the default in recent cursive. That would remove annoying external dependency.

**Comment by timdubbins** [comment]
Thanks for the suggestion. I was getting some UI flickering when using crossterm backend and since switching to ncurses resolved this I stuck with it. Cursive (and I'm guessing crossterm also) has changed quite a bit since then so I think this would be worth revisiting. It would be nice to get rid of the ncurses dep

**Comment by zkvsky** [comment]
> Thanks for the suggestion. I was getting some UI flickering when using crossterm backend and since switching to ncurses resolved this I stuck with it. Cursive (and I'm guessing crossterm also) has changed quite a bit since then so I think this would be worth revisiting. It would be nice to get rid of the ncurses dep

Definitely, crossterm seems to be widely adopted nowadays.
I've been working with ratatui/crossterm quite extensively, and have no flickering, dunno about cursive.

**Comment by hxlnt** [comment]
FYI, still seeing this issue with v0.5.1 (M3, Sequoia 15.5). Tried the fixes listed here to no avail.

**Comment by timdubbins** [comment]
Thanks for the update. The 'dev' branch should now be a working version that fixes this. It uses crossterm instead of ncurses (as @zkvsky suggested). I will put it out as a release in the next few days. Ended up making quite a few changes in order to fix a screen tearing issue (the way we draw the player needed optimising). After a few dead ends I think this version should work well
